dist: bionic
language: minimal

services:
  - docker

env:
  global:
    - GRADLE_HOME=$HOME/.gradle

install: skip

before_script:
  - chmod +x gradlew

script:
  - docker-compose run gradle-build

before_cache:
  - sudo chown -R $USER:$USER $GRADLE_HOME
  - rm -fr $GRADLE_HOME/caches/*/plugin-resolution/
  - ls -l $GRADLE_HOME/caches/ | grep -o -P "\d+\.\d+\.\d+\S*$" | xargs -I {} rm -rf $GRADLE_HOME/caches/{}
  - find $GRADLE_HOME/ -name "*.lock" | xargs -I {} rm -f {}

cache:
  directories:
    - $GRADLE_HOME/caches/
    - $GRADLE_HOME/wrapper/
