dist: bionic
language: minimal

services:
  - docker

env:
  global:
    - GRADLE_HOME="$HOME/.gradle"
    - TERM="dumb"
    - STATIC_WEB_FILES_DIR="/tmp/webtris"

jobs:
  include:

    - stage: test
      install: skip
      before_script:
        - chmod +x ./gradlew
      script:
        - docker-compose run gradle-build
      before_cache:
        - rm -f "$GRADLE_HOME/caches/modules-2/modules-2.lock"
        - rm -rf "$GRADLE_HOME/caches/*/plugin-resolution/"
      cache:
        directories:
          - "$GRADLE_HOME/caches/"
          - "$GRADLE_HOME/wrapper/"

    - stage: deploy
      if: branch = multiplatform
      before_install:
        - echo "$WEBTRIS_RSA_PRIVATE" > /tmp/rsa_secret
        - chmod 600 /tmp/rsa_secret
        - export GIT_SSH_COMMAND="ssh -i /tmp/rsa_secret"
      install:
        - git clone git@github.com:ndon55555/webtris.git "$STATIC_WEB_FILES_DIR"
      before_script:
        - chmod +x ./gradlew
      script:
        - find "$STATIC_WEB_FILES_DIR" -mindepth 1 -maxdepth 1 | grep --invert-match --regexp "/\.git" --regexp "/README.md" | xargs rm -rf
        - WEB_DIR="$STATIC_WEB_FILES_DIR" docker-compose run gradle-assemble-web
        - pushd "$STATIC_WEB_FILES_DIR"
        - git add --all && (git commit --message "Travis CI push" || true) && git push
        - popd
      before_cache:
        - rm -f "$GRADLE_HOME/caches/modules-2/modules-2.lock"
        - rm -rf "$GRADLE_HOME/caches/*/plugin-resolution/"
      cache:
        directories:
          - "$GRADLE_HOME/caches/"
          - "$GRADLE_HOME/wrapper/"