dist: bionic
language: minimal

services:
  - docker

env:
  global:
    - GRADLE_HOME="$HOME/.gradle"
    - TERM="dumb"

jobs:
  include:

    - stage: test
      install: skip
      before_script:
        - chmod +x ./gradlew
      script:
        - docker-compose run gradle-build
      before_cache:
        - rm -f "$GRADLE_HOME/caches/modules-2/modules-2.lock"
        - rm -rf "$GRADLE_HOME/caches/*/plugin-resolution/"
      cache:
        directories:
          - "$GRADLE_HOME/caches/"
          - "$GRADLE_HOME/wrapper/"

    - stage: deploy
      if: branch = multiplatform
      before_install:
        - echo "$WEBTRIS_RSA_PRIVATE" > /tmp/rsa_secret
        - chmod 600 /tmp/rsa_secret
        - export GIT_SSH_COMMAND="ssh -i /tmp/rsa_secret"
      install:
        - git clone git@github.com:ndon55555/webtris.git ./web
      before_script:
        - chmod +x ./gradlew
      script:
        - find web/* | grep --invert-match --regexp "*/\.*" --regexp "*README.md" | rm -rf
        - docker-compose run gradle-assemble-web
        - pushd ./web
        - git add --all && ((git commit --message "Travis CI push" && git push) || true)
        - popd
      before_cache:
        - rm -f "$GRADLE_HOME/caches/modules-2/modules-2.lock"
        - rm -rf "$GRADLE_HOME/caches/*/plugin-resolution/"
      cache:
        directories:
          - "$GRADLE_HOME/caches/"
          - "$GRADLE_HOME/wrapper/"