dist: bionic
language: minimal

services:
  - docker

env:
  global:
    - CC_TEST_REPORTER_ID=68b415548340539e4daeee8e0523652c47c5f451ac0cc61d1e54fdedc7d598b6
    - JACOCO_SOURCE_PATH=src/
    - GRADLE_HOME=$HOME/.gradle

install: skip

before_script:
  - chmod +x gradlew
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - >
    docker run
    -v "$(pwd)":/repo
    -v "$GRADLE_HOME":"$GRADLE_HOME"
    openjdk:12
    bash -c "cd /repo
    && ./gradlew build -g $GRADLE_HOME --scan --stacktrace --build-cache --parallel
    && ./gradlew --stop"
  - ./cc-test-reporter format-coverage build/reports/jacoco/test/jacocoTestReport.xml --input-type jacoco
  - ./cc-test-reporter upload-coverage

before_cache:
  - sudo chown -R $USER:$USER $GRADLE_HOME
  - rm -f  $GRADLE_HOME/caches/modules-2/modules-2.lock
  - rm -fr $GRADLE_HOME/caches/*/plugin-resolution/
  - ls -l $GRADLE_HOME/caches/ | grep -o -P "\d+\.\d+\.\d+\S*$" | xargs -I {} rm -rf $GRADLE_HOME/caches/{}
  - find $GRADLE_HOME/ -name "*.lock" | xargs -I {} rm -f {}

cache:
  directories:
    - $GRADLE_HOME/caches/
    - $GRADLE_HOME/wrapper/
