version: "3.7"

services:
  # Run tests
  gradle-build:
    image: openjdk:12
    environment:
      - TERM=dumb
    volumes:
      - .:/repo
      - $GRADLE_HOME:$GRADLE_HOME
    command: >
      sh -c "cd /repo
      && ./gradlew build --gradle-user-home $GRADLE_HOME --stacktrace --build-cache --parallel"

  # Create browser files
  gradle-assemble-web:
    image: openjdk:12
    environment:
      - TERM=dumb
      - WEB_DIR=$WEB_DIR
      - DEV_MODE=false
    volumes:
      - .:/repo
      - $GRADLE_HOME:$GRADLE_HOME
      - $WEB_DIR:$WEB_DIR
    command: >
      sh -c "cd /repo
      && ./gradlew :browser:assembleWeb --gradle-user-home $GRADLE_HOME --build-cache"