version: "3.7"

services:
  # Run tests
  gradle-build:
    image: openjdk:12
    environment:
      - TERM=dumb
    volumes:
      - .:/repo
      - $GRADLE_HOME:$GRADLE_HOME
    command: >
      sh -c "cd /repo
      && ./gradlew build --gradle-user-home /home/.gradle --stacktrace --build-cache --parallel
      && ./gradlew --stop"
  # Create browser files
  gradle-assemble-web:
    image: openjdk:12
    environment:
      - TERM=dumb
      - WEB_DIR=$WEB_DIR
    volumes:
      - .:/repo
      - $GRADLE_HOME:$GRADLE_HOME
    command: >
      sh -c "cd /repo && DEV_MODE=false ./gradlew :browser:assembleWeb"