name: "Setup Gradle"
description: "Prepares the environment for running Gradle tasks"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: "12"

    - name: Cache Gradle
      uses: burrunan/gradle-cache-action@v1

    - name: Ensure Gradle script executable
      run: chmod +x ./gradlew