on: push
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: "12"

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v1

      - name: Ensure Gradle script executable
        run: chmod +x ./gradlew

      - run: docker-compose run gradle-build

  deploy:
    name: Deploy Webtris
    # if: ${{ github.ref == 'refs/heads/multiplatform' }} TODO: uncomment this
    needs: test
    runs-on: ubuntu-18.04
    steps:
      - run: echo "${{ github.ref }}"
      - uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: "12"

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v1

      - name: Ensure Gradle script executable
        run: chmod +x ./gradlew

      - name: Create Web Files Dir
        run: echo "WEB_DIR=$(mktemp -d)" >> "$GITHUB_ENV"

      - name: Generate Web Files
        run: docker-compose run gradle-assemble-web

      - name: Create Deploy Key File
        run: echo "WEB_DEPLOY_KEY_FILE=$(mktemp)" >> "$GITHUB_ENV"

      - name: Setup Git SSH with Deploy Key
        run: |
          echo "${{ secrets.WEBTRIS_PRIVATE_DEPLOY_KEY }}" > "$WEB_DEPLOY_KEY_FILE"
          chmod 600 "$WEB_DEPLOY_KEY_FILE"
          export GIT_SSH_COMMAND="ssh -i $WEB_DEPLOY_KEY_FILE"

      - name: Publish Web Files
        uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
        with:
          destination_branch: "master"
          destination_repo: "ndon55555/webtris"
          source_file: "${{ env.WEB_DIR }}"/*
          user_email: "ndon55555@gmail.com"
          user_name: "ndon55555"
