on: push
jobs:
  pre-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            .github/**
            **/build.gradle.kts
            **/*.kt
            **/*.lockfile

  test:
    runs-on: ubuntu-18.04
    needs: pre-test
    if: ${{ env.GIT_DIFF }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: "12"

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v1

      - name: Ensure Gradle script executable
        run: chmod +x ./gradlew

      - run: docker-compose run gradle-build

  deploy:
    name: Deploy Webtris
    needs: test
    if: ${{ github.ref == 'refs/heads/multiplatform' }}
    runs-on: ubuntu-18.04
    steps:
      - run: echo "${{ github.ref }}"
      - uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: "12"

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v1

      - name: Ensure Gradle script executable
        run: chmod +x ./gradlew

      - name: Create Web Files Dir
        run: echo "WEB_DIR=$(mktemp -d)" >> "$GITHUB_ENV"

      - name: Generate Web Files
        run: docker-compose run gradle-assemble-web

      - name: Publish Web Files
        uses: s0/git-publish-subdir-action@v2.4.0
        env:
          REPO: git@github.com:ndon55555/webtris.git
          BRANCH: master
          FOLDER: ${{ env.WEB_DIR }}
          SSH_PRIVATE_KEY: ${{ secrets.WEBTRIS_PRIVATE_DEPLOY_KEY }}
          SKIP_EMPTY_COMMITS: true
